spring.application.name=senior

# URL de conexión a postgreSQL
spring.datasource.url = jdbc:postgresql://localhost:5432/veterinaria

# Usuario de la base de datos
spring.datasource.username= postgres

#contraseña
spring.datasource.password = admin123